apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  labels:
    app: journal-api
spec:
  selector:
    app: journal-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer
